#!/usr/bin/env python3
"""Inline the shared site chrome into every page under pages/ (recursively).

Source of truth
  shared/header.html          header stack (nav-utility +
                              navigation-header with the project nav items)
  shared/footer.html          visual footer
  shared/chrome.css           CSS companions the chrome markup depends on
  shared/chrome-scripts.html  chrome-driven shadow injections

Run after editing anything in shared/:
    python3 scripts/build-chrome.py

Why this exists
  The chrome used to be copy-pasted into all seven pages, and its CSS lived in
  a different place from its markup. Building a page's <head> from
  page-builder/TEMPLATE.html while copying the chrome markup from a sibling
  page silently dropped the CSS companions: no console error, no broken
  layout, just unstyled chrome. Markup, CSS, and scripts now travel together.

How it works
  Each region is delimited by SHARED:<key>:START / :END comments. On the first
  run the markers do not exist yet, so the script LOCATES the existing region
  by content and wraps it (migration). On later runs it simply replaces what is
  between the markers. Both paths are idempotent.

  Pages generated by scripts/build-programs.py and
  scripts/build-colleges-schools.py read the same shared/ files, so running
  either of those or this one converges on the same bytes.

--check exits non-zero if any page would change, without writing.
"""
import glob
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _chrome

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHARED = os.path.join(REPO, 'shared')
# Pages live in per-section subdirectories (pages/academics/programs.html) as
# well as at the top (pages/admissions.html), so this walks the tree; each page
# gets the chrome resolved for its own depth.
PAGES = sorted(glob.glob(os.path.join(REPO, 'pages', '**', '*.html'), recursive=True))

CHECK = '--check' in sys.argv




# ---------------------------------------------------------------- CSS helpers
def css_rules(css):
    """Split a stylesheet into top-level rules, keeping each rule's leading comment."""
    out, depth, buf = [], 0, ''
    for ch in css:
        buf += ch
        if ch == '{':
            depth += 1
        elif ch == '}':
            depth -= 1
            if depth == 0:
                out.append(buf.strip())
                buf = ''
    if buf.strip():
        out.append(buf.strip())
    return out


def selector(rule):
    return re.sub(r'/\*.*?\*/', '', rule.split('{')[0], flags=re.S).strip()


CHROME_SELECTORS = ('utility-navigation', 'umd-element-scroll-top')


def strip_chrome_css(src):
    """Remove chrome rules from the page's own <style> blocks (migration only).

    They are re-emitted from shared/chrome.css in a dedicated marked block, so
    leaving the originals in place would duplicate them.
    """
    blocks = list(re.finditer(r'(?s)<style>(.*?)</style>', src))
    if len(blocks) < 2:
        return src, 0
    removed = 0
    # Walk backwards so earlier match offsets stay valid.
    for m in reversed(blocks[1:]):
        body = m.group(1)
        keep, drop = [], 0
        for rule in css_rules(body):
            if any(k in selector(rule) for k in CHROME_SELECTORS):
                drop += 1
            else:
                keep.append(rule)
        if not drop:
            continue
        removed += drop
        if keep:
            new = '<style>\n    ' + '\n\n    '.join(keep) + '\n  </style>'
        else:
            new = ''  # block held nothing but chrome rules
        src = src[:m.start()] + new + src[m.end():]
    return src, removed


def strip_chrome_script(src):
    """Remove the nav-header logo injection from the page's own <script> block."""
    pat = re.compile(
        r'\n?[ \t]*// NAV-HEADER LOGO WIDTH.*?\n[ \t]*\}\)\(\);\n', re.S)
    src, n = pat.subn('\n', src)
    return src, n


# ---------------------------------------------------------------- splice
def splice(src, key, locate, page):
    block = _chrome.block(key, page)

    m = re.search(r'(?s)[ \t]*<!-- SHARED:%s:START.*?<!-- SHARED:%s:END -->' % (key, key), src)
    if m:
        if src[m.start():m.end()] == block:
            return src, 'unchanged'
        if not block:
            # An optional region whose source file was deleted: take the
            # block's own trailing newline with it, or removing it leaves a
            # blank line behind on every page.
            end = m.end() + 1 if src[m.end():m.end() + 1] == '\n' else m.end()
            return src[:m.start()] + src[end:], 'removed'
        return src[:m.start()] + block + src[m.end():], 'updated'

    if not block:
        # Nothing to insert and no markers to clean up. Without this the
        # zero-width insertion below would add a blank line on every run.
        return src, 'absent'

    span = locate(src)
    if span is None:
        return src, 'absent'
    a, b = span
    # A zero-width span is a pure insertion (the region has no existing markup
    # to replace); it needs its own trailing newline, or the block runs into
    # whatever follows — e.g. "<!-- SHARED:chrome-css:END --></head>".
    tail = '\n' if a == b else ''
    return src[:a] + block + tail + src[b:], 'migrated'


def find_between(src, start_re, end_re):
    a = re.search(start_re, src)
    if not a:
        return None
    b = re.search(end_re, src[a.start():])
    if not b:
        return None
    return a.start(), a.start() + b.end()


def locate_header(src):
    return find_between(src,
                        r'[ \t]*<umd-element-navigation-utility\b[^>]*data-alert-off',
                        r'</umd-element-navigation-header>')


def locate_footer(src):
    return find_between(src, r'[ \t]*<umd-element-footer\b', r'</umd-element-footer>')


def locate_css_slot(src):
    """Insert a new chrome-CSS block immediately before </head>."""
    m = re.search(r'\n</head>', src)
    return (m.start() + 1, m.start() + 1) if m else None


def locate_gate_slot(src):
    """Insert the access gate immediately before </head>.

    Runs after chrome-css in the splice order below, so on a page that has
    neither yet the gate lands after the chrome CSS -- matching the pages that
    were gated by hand. Order does not actually matter here (the gate's
    selectors are on html/body and share nothing with the chrome rules), but
    keeping it stable is what lets --check stay quiet.
    """
    m = re.search(r'\n</head>', src)
    return (m.start() + 1, m.start() + 1) if m else None


def locate_script_slot(src):
    """Insert the chrome scripts immediately before </body>."""
    m = re.search(r'\n</body>', src)
    return (m.start() + 1, m.start() + 1) if m else None


# ---------------------------------------------------------------- run
changed, report = [], []
for path in PAGES:
    original = open(path, encoding='utf-8').read()
    src = original
    notes = []

    migrating_css = 'SHARED:chrome-css:START' not in src
    if migrating_css:
        src, n = strip_chrome_css(src)
        if n:
            notes.append('stripped %d inline chrome rule(s)' % n)
    migrating_js = 'SHARED:chrome-scripts:START' not in src
    if migrating_js:
        src, n = strip_chrome_script(src)
        if n:
            notes.append('stripped inline nav-logo injection')

    for key, locate in (
            ('header', locate_header),
            ('footer', locate_footer),
            ('chrome-css', locate_css_slot),
            ('gate', locate_gate_slot),
            ('chrome-scripts', locate_script_slot),
    ):
        src, status = splice(src, key, locate, path)
        if status not in ('unchanged',):
            notes.append('%s:%s' % (key, status))

    name = os.path.relpath(path, REPO)
    if src != original:
        changed.append(name)
        if not CHECK:
            open(path, 'w', encoding='utf-8').write(src)
    report.append((name, 'CHANGED' if src != original else 'ok', notes))

w = max(len(n) for n, _, _ in report)
for name, status, notes in report:
    print('  %-*s  %-8s %s' % (w, name, status, '; '.join(notes)))

print('\n%d/%d page(s) %s' % (len(changed), len(PAGES),
                              'would change' if CHECK else 'written'))
if CHECK and changed:
    sys.exit(1)
